"""empty message

Revision ID: dacbfb0a95f2
Revises: 
Create Date: 2022-11-27 14:52:40.208313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacbfb0a95f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('id_libro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_libro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros')
    # ### end Alembic commands ###
